/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class maspack_solvers_CuDssSolver */

#ifndef _Included_maspack_solvers_CuDssSolver
#define _Included_maspack_solvers_CuDssSolver
#ifdef __cplusplus
extern "C" {
#endif
#undef maspack_solvers_CuDssSolver_MT_GENERAL
#define maspack_solvers_CuDssSolver_MT_GENERAL 0L
#undef maspack_solvers_CuDssSolver_MT_SYMMETRIC
#define maspack_solvers_CuDssSolver_MT_SYMMETRIC 1L
#undef maspack_solvers_CuDssSolver_MT_SPD
#define maspack_solvers_CuDssSolver_MT_SPD 2L
#undef maspack_solvers_CuDssSolver_UNSET
#define maspack_solvers_CuDssSolver_UNSET 0L
#undef maspack_solvers_CuDssSolver_ANALYZED
#define maspack_solvers_CuDssSolver_ANALYZED 1L
#undef maspack_solvers_CuDssSolver_FACTORED
#define maspack_solvers_CuDssSolver_FACTORED 2L
#undef maspack_solvers_CuDssSolver_INIT_UNKNOWN
#define maspack_solvers_CuDssSolver_INIT_UNKNOWN 0L
#undef maspack_solvers_CuDssSolver_INIT_OK
#define maspack_solvers_CuDssSolver_INIT_OK 1L
#undef maspack_solvers_CuDssSolver_ERR_CANT_LOAD_LIBRARIES
#define maspack_solvers_CuDssSolver_ERR_CANT_LOAD_LIBRARIES -1L
/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_maspack_solvers_CuDssSolver_doInit
  (JNIEnv *, jclass);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doSetPattern
 * Signature: (JII[I[II)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doSetPattern
  (JNIEnv *, jclass, jlong, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAnalyze
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAnalyze
  (JNIEnv *, jclass, jlong);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doFactor
 * Signature: (J[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doFactor
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doClearDeviceValues
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doClearDeviceValues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doGetDeviceValues
 * Signature: (J[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doGetDeviceValues
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddDeviceValues
 * Signature: (J[I[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddDeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddScaledDiagonal3DeviceValues
 * Signature: (J[I[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddScaledDiagonal3DeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddScaledBlock3DeviceValues
 * Signature: (J[I[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddScaledBlock3DeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddMaterialStiffness3DeviceValues
 * Signature: (J[I[D[D[D[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddMaterialStiffness3DeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddMaterialStiffness3ElementDeviceValues
 * Signature: (J[I[I[I[I[I[I[D[D[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddMaterialStiffness3ElementDeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddLinearElasticStiffness3ElementDeviceValues
 * Signature: (J[I[I[I[I[I[I[D[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddLinearElasticStiffness3ElementDeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddLinearElasticStiffness3ElementGeometryDeviceValues
 * Signature: (J[I[I[I[I[I[I[I[I[D[D[D[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddLinearElasticStiffness3ElementGeometryDeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doAddDilationalStiffness3ElementDeviceValues
 * Signature: (J[I[I[I[I[I[I[I[D[DID)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doAddDilationalStiffness3ElementDeviceValues
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jdoubleArray, jdoubleArray, jint, jdouble);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doFactorDeviceValues
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doFactorDeviceValues
  (JNIEnv *, jclass, jlong);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doSolve
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doSolve
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doMultiply
 * Signature: (J[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doMultiply
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doSolveMulti
 * Signature: (JI[D[D)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doSolveMulti
  (JNIEnv *, jclass, jlong, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doIterativeSolve
 * Signature: (J[D[D[DDI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doIterativeSolve
  (JNIEnv *, jclass, jlong, jdoubleArray, jdoubleArray, jdoubleArray, jdouble, jint);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_CuDssSolver_doDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doGetLastError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_maspack_solvers_CuDssSolver_doGetLastError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_maspack_solvers_CuDssSolver_doGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doSetTimingEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_maspack_solvers_CuDssSolver_doSetTimingEnabled
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     maspack_solvers_CuDssSolver
 * Method:    doSetIrSteps
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_maspack_solvers_CuDssSolver_doSetIrSteps
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
